### ISSUE TITLE
no github page

### ISSUE THREAD

**Issue by tectrixdev** [ilxplay/tripleR#1]
please add github page

**Comment by ilxplay** [comment]
> please add github page


It's a potential feature I could realise.

**Comment by tectrixdev** [comment]
It's not really a feature but more required as of now since you have no build instructions, no list of dependencies or any way of running it(without spending too much time figuring out the dependencies etc...)

**Comment by tectrixdev** [comment]
Completed?? I don't see any GitHub page?
